In [ ]:
import pandas as pd
movies_data = pd.read_csv('https://raw.githubusercontent.com/podkovko/ds_course/refs/heads/main/Data%20Science%20Course/PY_12%20%D0%9F%D1%80%D0%BE%D0%B4%D0%B2%D0%B8%D0%BD%D1%83%D1%82%D1%8B%D0%B5%20%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B%20%D1%81%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%BC%D0%B8%20%D0%B2%20Pandas/data/ratings_movies.csv')
movies = movies_data.copy()
import re 
def get_year_release(arg):
    candidates = re.findall(r'\(\d{4}\)', arg) 
    if len(candidates) > 0:
        year = candidates[0].replace('(', '')
        year = year.replace(')', '')
        return int(year)
    else:
        return None

# Задание 8.1
movies['year release'] = movies['title'].apply(get_year_release)
movies['year release'].isna().sum()

# Задание 8.2
mean_ratings_1999 = movies[movies['year release'] == 1999].groupby(by='title')['rating'].mean().sort_values()

# Задание 8.3
genre_ratings_2010 = movies[movies['year release'] == 2010].pivot_table(
    values='rating',
    index='genres',
)
genre_ratings_2010 = genre_ratings_2010.sort_values('rating')

# Задание 8.4
user_genres = movies.pivot_table(
    index='userId',
    columns='genres',
    aggfunc='count'
)
user_genre_count = pd.DataFrame()
user_genre_count['Count'] = user_genres.notna().sum(axis=1).sort_values()

# Задание 8.5
user_analysis = movies.groupby('userId')['rating'].agg(
    ['count', 'mean']
).sort_values(by=['count', 'mean'], ascending=[True, False])

# Задание 8.6
mask1 = movies['year release'] == 2018
genre_analysis = movies[mask1].groupby('genres')['rating'].agg(
    ['mean', 'count']
).sort_values(by=['mean'])
mask2 = genre_analysis['count'] > 10
genre_analysis = genre_analysis[mask2]

# Задание 8.7
movies['date'] = pd.to_datetime(movies['date'])
movies['year_rating'] = movies['date'].dt.year
year_genre = movies.pivot_table(
    values='rating',
    index='genres',
    columns='year_rating'
)
display(year_genre)

year_genre.loc['Action|Adventure'].min()
year_genre.loc['Action|Adventure|Animation|Children|Comedy|IMAX'].sort_values(ascending=False)
year_genre.loc['Comedy']

year_rating,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
genres,,,,,,,,,,,,,,,,,,,,,
(no genres listed),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,3.500000,3.000000,3.676471
Action,2.730769,3.538462,NaN,NaN,2.588235,3.000000,2.750000,3.833333,2.700000,3.357143,...,NaN,3.500000,4.500000,2.625000,2.500000,NaN,3.100000,3.545455,2.637931,2.588235
Action|Adventure,3.454545,4.150000,4.2,4.0,3.738462,3.500000,4.304348,3.277778,4.136364,3.413043,...,3.714286,3.437500,3.888889,3.900000,3.833333,3.875,3.560976,3.722222,3.527778,3.397436
Action|Adventure|Animation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.000,3.800000,3.750000,3.375000,3.650000
Action|Adventure|Animation|Children,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4.000000,3.000000,3.500,3.666667,3.833333,3.500000,3.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sci-Fi|Thriller,2.666667,3.400000,NaN,4.0,2.142857,2.500000,3.600000,3.142857,NaN,2.750000,...,4.000000,2.500000,1.833333,3.500000,3.833333,NaN,3.764706,3.916667,3.750000,3.562500
Sci-Fi|Thriller|IMAX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4.000000,3.666667,4.000000,4.000,4.000000,3.666667,2.500000,NaN
Thriller,3.838095,3.923077,3.8,3.7,3.087912,3.477273,3.583333,3.250000,3.464286,3.411765,...,2.964286,2.833333,3.625000,3.083333,3.666667,4.000,2.911765,3.432432,3.152174,3.296296
War,NaN,NaN,NaN,4.5,3.000000,3.000000,3.500000,3.000000,3.000000,NaN,...,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Western,3.117647,3.000000,NaN,4.0,4.058824,3.111111,3.000000,4.000000,3.800000,4.500000,...,3.375000,3.666667,4.000000,4.100000,4.000000,4.000,3.900000,3.958333,2.933333,3.611111

year_rating
1996    3.228571
1997    3.409091
1998    3.000000
1999    3.606061
2000    3.141291
2001    3.318408
2002    3.198556
2003    3.120066
2004    3.356877
2005    2.963325
2006    3.347534
2007    2.928187
2008    3.426667
2009    3.273292
2010    3.179825
2011    3.232877
2012    3.478477
2013    3.489474
2014    3.271429
2015    3.106183
2016    3.373431
2017    2.852668
2018    3.121296
Name: Comedy, dtype: float64